// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrMTPiExfnLaVR1DDdXBaoGRuMaYxju8M',
    appId: '1:882662842988:web:dec2e64a162a0007256e49',
    messagingSenderId: '882662842988',
    projectId: 'fir-firebase-55f1e',
    authDomain: 'fir-firebase-55f1e.firebaseapp.com',
    storageBucket: 'fir-firebase-55f1e.firebasestorage.app',
    measurementId: 'G-DZ9L74DQLG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOh_8eaxbsIDFhMK9HLZMqUy698LiFPro',
    appId: '1:882662842988:android:e01017e1bd13f253256e49',
    messagingSenderId: '882662842988',
    projectId: 'fir-firebase-55f1e',
    storageBucket: 'fir-firebase-55f1e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANMYO7XZxHt6XPZLtOpEbRJTs_mQGe3PA',
    appId: '1:882662842988:ios:6cca8b2e0c64614c256e49',
    messagingSenderId: '882662842988',
    projectId: 'fir-firebase-55f1e',
    storageBucket: 'fir-firebase-55f1e.firebasestorage.app',
    iosBundleId: 'com.example.prac1112Firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANMYO7XZxHt6XPZLtOpEbRJTs_mQGe3PA',
    appId: '1:882662842988:ios:6cca8b2e0c64614c256e49',
    messagingSenderId: '882662842988',
    projectId: 'fir-firebase-55f1e',
    storageBucket: 'fir-firebase-55f1e.firebasestorage.app',
    iosBundleId: 'com.example.prac1112Firebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBrMTPiExfnLaVR1DDdXBaoGRuMaYxju8M',
    appId: '1:882662842988:web:aef7611793e7c53c256e49',
    messagingSenderId: '882662842988',
    projectId: 'fir-firebase-55f1e',
    authDomain: 'fir-firebase-55f1e.firebaseapp.com',
    storageBucket: 'fir-firebase-55f1e.firebasestorage.app',
    measurementId: 'G-NNT0C89E5P',
  );
}
